export const animalsMock = [
  {
    rgd: 'ALENIA3FJSJ',
    nome: 'ALENIA3FJSJ',
    sexo: 'F',
    nascimento: '07/01/2023',
    pai: 'SID/PO JTSJ 383',
    mae: 'SID/PA A4259',
    status: 'Pendente',
    ultimoParto: '15/01/2024',
  },
  {
    rgd: 'ADILSON1FJSJ',
    nome: 'ADILSON1FJSJ',
    sexo: 'M',
    nascimento: '25/05/2023',
    pai: 'SID/PO JTSJ 383',
    mae: 'SID/PA A1702',
    status: 'Pendente',
    ultimoParto: '-',
  },
  {
    rgd: 'CALIGRAFIA6MLGS',
    nome: 'CALIGRAFIA6MLGS',
    sexo: 'F',
    nascimento: '18/06/2023',
    pai: 'SID/PO BDS 292',
    mae: 'SID/PA A4254',
    status: 'RG D',
    ultimoParto: '10/01/2024',
  },
  {
    rgd: 'BOMBEIRO SARAIVA65FJSS',
    nome: 'BOMBEIRO SARAIVA65FJSS',
    sexo: 'M',
    nascimento: '12/07/2023',
    pai: 'SID/PC RM1',
    mae: 'SID/PO JTSJ 269',
    status: 'Pendente',
    ultimoParto: '-',
  },
]